version: "3.1"
services:
    pagination-php:
        build: tools/docker/php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./tools/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini